Requirements:
-------------
To build the COLLADAStreamWriter, you need following installations:
- 	Boost C++ libraries

Supported versions of boost c++ libraries:
-	Boost 1.35

You also need a c++ compiler. The current Project was build with 
Microsoft Visual Studio 2005 and the VC2005 platform SDK. You can 
find the vs project file in the "scripts" directory.


Build:
---------
Before you can start to build you have to define following environment 
variables: 
-	"BOOST_ROOT" to your installation path of boost

Download and compile the sources of COLLADAStreamWriter as a static library. 
The "COLLADAStreamWriter.lib" file will be created in the "lib" directory. 
The COLLADAMaya and COLLADAMax plug-ins will use it there.
