Requirements:
-------------
To build the COLLADAMaya plug-in, you need following installations:
-	Autodesk Maya, including the SDK
- 	boost c++ libraries


Supported versions of Autodesk Maya are:
-	Autodesk Maya 2008

Supported versions of boost c++ libraries:
-	boost 1.35


You also need a c++ compiler. The current Project was build with 
Microsoft Visual Studio 2005. You can find the visual studio project file in 
the COLLADAMaya directory ./scripts.


Build:
---------
Before you can start to build you have to define following environment 
variables: 
-	"MAYA_PATH2008" to your installation path of Autodesk Maya
-	"BOOST_ROOT" to your installation path of boost

Download and compile the sources of COLLADAMaya. The "COLLADAMaya.mll" file 
will be created in the output folder and copied into the folder 
$(MAYA_PATH2008)/bin/plug-ins of your Autodesk Maya installation.

If you don't use the MS Visual Studio project file, you have to copy the 
created "COLLADAMaya.mll" file into this directory.

For help on installation, please read the INSTALL file.