Requirements:
-------------
To build the COLLADAMaya plug-in, you need a version of Autodesk Maya, 
including the SDK, installed.

Supported versions are:
Autodesk Maya 2008

You also need a c++ compiler. The current Project was build with 
Microsoft Visual Studio 2005. You can find the visual studio project file in 
the COLLADAMaya directory ./scripts.


Build:
---------
Before you can start to build you have to define the environment variable 
"MAYA_PATH2008" to your installation path of Autodesk Maya.

Download and compile the sources of COLLADAMaya. The "COLLADAMaya.mll" file 
will be created in the output folder and copied into the folder 
$(MAYA_PATH2008)/bin/plug-ins of your Autodesk Maya installation.

If you don't use the MS Visual Studio project file, you have to copy the 
created "COLLADAMaya.mll" file into this directory.

For help on installation, please read the INSTALL file.