
Import('env')

libName = 'ftoa'


srcFiles = [ 'Commondtoa.cpp', 'Commonftoa.cpp', 'Commonitoa.cpp' ]
srcDir = 'src/'

variantDir = env['objDir']  + env['configurationBaseName'] + '/'
outputDir =  env['libDir']  + env['configurationBaseName'] + '/'
targetPath = outputDir + libName


incDirs = ['include/']


src = [ variantDir + srcDir + file for file in srcFiles ]   
VariantDir(variant_dir=variantDir + srcDir, src_dir=srcDir, duplicate=False)

if env['SHAREDLIB']:
    SharedLibrary(target=targetPath, source=src, CPPPATH=incDirs, CCFLAGS=env['CPPFLAGS'])
else:
    StaticLibrary(target=targetPath, source=src, CPPPATH=incDirs, CCFLAGS=env['CPPFLAGS'])
